### ISSUE TITLE
Assets Checksum Not Matched

### ISSUE THREAD

**Issue by GinMinowa** [The-Brave-Clab/Jinchoge#9]
Hi, the MD5 of 
`/android/sound/card_303600.acb` --- e07ebec01582d78daa29f9c902cdbac8
`/android/sound/es061_001_m004_a.acb` --- daff3ce9e87720d591bcd0e5986a2607
`/ios/sound/card_303600.acb` --- e07ebec01582d78daa29f9c902cdbac8
`/ios/sound/es061_001_m004_a.acb` --- daff3ce9e87720d591bcd0e5986a2607
in your bucket are different from the records in `sound.json`. The MD5 of *card_303600.acb* record in `sound.json` is `C043D9C5708A11A548CBA5071D65B35A` and *es061_001_m004_a.acb* record in `sound.json` is `4D7C00D441331BDCB8D58B29C7AA916C`. Since CriWave seems doesn't have checksum in container files, can you help me check whether are the files demaged or you modified them for some reasons? Thanks for your private server so I can replay such a wonderful game.

**Comment by shurunxuan** [comment]
Good catch and yes you are absolutely correct about mismatching MD5 checksum.

However, both the files and the JSON metadata are not modified, which means that they have been wrong all the time with the official server. I found this when running my datamining scripts that these files just keep redownloading every time.

I thought about fixing them in the private server, but I chose to stick with the original behavior of the official server to prevent some maintenance hell. So this will not be fixed.

Thank you for pointing out though!
